# Site settings
title: Patrick Gault
email: PatrickGaultAtGmail
url: pgault.github.io
description: "This is Patrick Gault's personal website."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/gaultpatrick
  - title: twitter
    url: https://twitter.com/PatricktGault
  - title: github
    url: https://github.com/patrickgault

# Build settings
markdown: kramdown
permalink: pretty
