# Site settings
title: Patrick Gault
email: PatrickGaultAtGmail
description: > # this means to ignore newlines until "baseurl:"
baseurl: /patrickgault # the subpath of your site, e.g. /blog/
url: patrickgault.github.io # the base hostname & protocol for your site

twitter_username: patricktgault
github_username: patrickgault

# Build settings
markdown: kramdown
